from datetime import datetime
from pathlib import Path
from typing import Optional
from rich.console import Console

console = Console()

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Recon Report — {target}</title>
<style>
  :root {{
    --bg: #0d1117;
    --bg2: #161b22;
    --bg3: #21262d;
    --border: #30363d;
    --text: #c9d1d9;
    --text-dim: #8b949e;
    --cyan: #58a6ff;
    --green: #3fb950;
    --red: #f85149;
    --yellow: #d29922;
    --orange: #db6d28;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: var(--bg);
    color: var(--text);
    font-family: 'Segoe UI', system-ui, -apple-system, monospace;
    min-height: 100vh;
    padding: 2rem;
  }}
  header {{
    border-bottom: 1px solid var(--border);
    padding-bottom: 1.5rem;
    margin-bottom: 2rem;
  }}
  header h1 {{
    font-size: 1.8rem;
    color: var(--cyan);
    letter-spacing: -0.5px;
  }}
  header .meta {{
    color: var(--text-dim);
    font-size: 0.85rem;
    margin-top: 0.4rem;
  }}
  .badge {{
    display: inline-block;
    padding: 0.2rem 0.6rem;
    border-radius: 9999px;
    font-size: 0.75rem;
    font-weight: 600;
    background: var(--bg3);
    border: 1px solid var(--border);
    margin-left: 0.5rem;
  }}
  .stats {{
    display: flex;
    gap: 1rem;
    flex-wrap: wrap;
    margin-bottom: 2rem;
  }}
  .stat-card {{
    background: var(--bg2);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1rem 1.5rem;
    min-width: 160px;
    text-align: center;
  }}
  .stat-card .number {{
    font-size: 2rem;
    font-weight: 700;
    color: var(--cyan);
  }}
  .stat-card .label {{
    font-size: 0.8rem;
    color: var(--text-dim);
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin-top: 0.25rem;
  }}
  section {{
    background: var(--bg2);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 1.5rem;
    margin-bottom: 1.5rem;
  }}
  section h2 {{
    font-size: 1rem;
    color: var(--cyan);
    margin-bottom: 1rem;
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }}
  table {{
    width: 100%;
    border-collapse: collapse;
    font-size: 0.875rem;
  }}
  thead tr {{
    background: var(--bg3);
  }}
  th, td {{
    padding: 0.6rem 1rem;
    text-align: left;
    border-bottom: 1px solid var(--border);
  }}
  th {{
    color: var(--text-dim);
    font-weight: 600;
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover {{ background: var(--bg3); }}
  .tag-open {{ color: var(--green); font-weight: 600; }}
  .tag-closed {{ color: var(--text-dim); }}
  .tag-filtered {{ color: var(--yellow); }}
  .vuln-critical {{ color: var(--red); font-weight: 700; }}
  .vuln-high {{ color: var(--orange); font-weight: 600; }}
  .vuln-medium {{ color: var(--yellow); }}
  .vuln-low {{ color: var(--text-dim); }}
  .empty {{ color: var(--text-dim); font-style: italic; font-size: 0.875rem; }}
  .info-grid {{
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
    gap: 0.75rem;
  }}
  .info-item {{
    background: var(--bg3);
    border-radius: 6px;
    padding: 0.75rem 1rem;
  }}
  .info-item .key {{
    font-size: 0.7rem;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--text-dim);
    margin-bottom: 0.3rem;
  }}
  .info-item .val {{
    font-weight: 600;
    color: var(--text);
    word-break: break-all;
  }}
  footer {{
    text-align: center;
    color: var(--text-dim);
    font-size: 0.75rem;
    margin-top: 2rem;
    padding-top: 1rem;
    border-top: 1px solid var(--border);
  }}
  footer a {{ color: var(--cyan); text-decoration: none; }}
</style>
</head>
<body>
<header>
  <h1>Recon Report <span class="badge">{target}</span></h1>
  <div class="meta">Generated on {timestamp} &nbsp;|&nbsp; Tool: recon-toolkit v1.0.0</div>
</header>

<div class="stats">
  <div class="stat-card">
    <div class="number">{subdomain_count}</div>
    <div class="label">Subdomains</div>
  </div>
  <div class="stat-card">
    <div class="number">{open_ports_count}</div>
    <div class="label">Open Ports</div>
  </div>
  <div class="stat-card">
    <div class="number">{vuln_count}</div>
    <div class="label">CVEs (Shodan)</div>
  </div>
</div>

{shodan_section}

<section>
  <h2>Subdomains ({subdomain_count})</h2>
  {subdomains_table}
</section>

<section>
  <h2>Open Ports ({open_ports_count})</h2>
  {ports_table}
</section>

<footer>
  Generated by <a href="https://github.com/yourusername/recon-toolkit" target="_blank">recon-toolkit</a>
  &nbsp;|&nbsp; For authorized security testing only
</footer>
</body>
</html>
"""


class ReportGenerator:
    def __init__(
        self,
        target: str,
        subdomains: list[str],
        open_ports: dict[int, dict],
        shodan_data: Optional[dict] = None,
    ):
        self.target = target
        self.subdomains = subdomains
        self.open_ports = open_ports
        self.shodan_data = shodan_data

    def _subdomains_table(self) -> str:
        if not self.subdomains:
            return '<p class="empty">No subdomains found.</p>'
        rows = "".join(
            f"<tr><td>{i}</td><td>{sub}</td></tr>"
            for i, sub in enumerate(self.subdomains, 1)
        )
        return f"""
        <table>
          <thead><tr><th>#</th><th>Subdomain</th></tr></thead>
          <tbody>{rows}</tbody>
        </table>"""

    def _ports_table(self) -> str:
        if not self.open_ports:
            return '<p class="empty">No open ports found.</p>'
        rows = "".join(
            f'<tr><td>{port}</td><td><span class="tag-open">open</span></td>'
            f'<td>{info.get("service", "unknown")}</td></tr>'
            for port, info in sorted(self.open_ports.items())
        )
        return f"""
        <table>
          <thead><tr><th>Port</th><th>State</th><th>Service</th></tr></thead>
          <tbody>{rows}</tbody>
        </table>"""

    def _shodan_section(self) -> str:
        if not self.shodan_data:
            return ""

        d = self.shodan_data
        org = d.get("org", "N/A")
        isp = d.get("isp", "N/A")
        country = d.get("country_name", "N/A")
        city = d.get("city", "N/A")
        os_info = d.get("os", "N/A")
        hostnames = ", ".join(d.get("hostnames", [])) or "N/A"
        last_update = d.get("last_update", "N/A")

        info_grid = f"""
        <div class="info-grid">
          <div class="info-item"><div class="key">Organization</div><div class="val">{org}</div></div>
          <div class="info-item"><div class="key">ISP</div><div class="val">{isp}</div></div>
          <div class="info-item"><div class="key">Country</div><div class="val">{country}</div></div>
          <div class="info-item"><div class="key">City</div><div class="val">{city}</div></div>
          <div class="info-item"><div class="key">OS</div><div class="val">{os_info}</div></div>
          <div class="info-item"><div class="key">Hostnames</div><div class="val">{hostnames}</div></div>
          <div class="info-item"><div class="key">Last Update</div><div class="val">{last_update}</div></div>
        </div>"""

        # Vulnerabilities
        vulns = d.get("vulns", {})
        vuln_html = ""
        if vulns:
            rows = []
            for cve, info in list(vulns.items())[:50]:
                cvss = float(info.get("cvss", 0) or 0)
                if cvss >= 9:
                    cls = "vuln-critical"
                elif cvss >= 7:
                    cls = "vuln-high"
                elif cvss >= 4:
                    cls = "vuln-medium"
                else:
                    cls = "vuln-low"
                summary = str(info.get("summary", ""))[:120]
                rows.append(
                    f'<tr><td class="{cls}">{cve}</td>'
                    f'<td class="{cls}">{cvss}</td>'
                    f'<td>{summary}</td></tr>'
                )
            vuln_html = f"""
            <h2 style="margin-top:1rem">Known CVEs ({len(vulns)})</h2>
            <table>
              <thead><tr><th>CVE</th><th>CVSS</th><th>Summary</th></tr></thead>
              <tbody>{"".join(rows)}</tbody>
            </table>"""

        return f"""
        <section>
          <h2>Shodan Intelligence</h2>
          {info_grid}
          {vuln_html}
        </section>"""

    def generate(self, output_path: str = "report.html"):
        vulns = self.shodan_data.get("vulns", {}) if self.shodan_data else {}
        html = TEMPLATE.format(
            target=self.target,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            subdomain_count=len(self.subdomains),
            open_ports_count=len(self.open_ports),
            vuln_count=len(vulns),
            shodan_section=self._shodan_section(),
            subdomains_table=self._subdomains_table(),
            ports_table=self._ports_table(),
        )
        Path(output_path).write_text(html, encoding="utf-8")
        console.print(f"[green]Report generated:[/green] [bold white]{output_path}[/bold white]")
